[[servers]]
host = "freeipaserver"
port = 389
use_ssl = false
start_tls = false
ssl_skip_verify = true
timeout = 10

search_filter = "(uid=%s)"

bind_dn         = '$__env{LDAP_GRAFANA_BIND_DN}'
bind_password   = '$__env{LDAP_BIND_PASSWORD}'
search_base_dns = ['$__env{LDAP_DC}',]

[servers.attributes]
member_of = "memberOf"
email =  "email"

[[servers.group_mappings]]
group_dn = "cn=${LDAP_GROUP_GRAFANA},cn=groups,cn=accounts,${LDAP_DC}"
org_role = "Admin"
